services:
  - type: web
    name: backend-maquinaria
    env: node
    region: ohio
    plan: free
    buildCommand: |
      npm config set legacy-peer-deps true
      npm install --legacy-peer-deps
      npm run build
    startCommand: npm run start:prod
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: npm-cache
      mountPath: /opt/render/.cache
      sizeGB: 1